PruebaTecnicaJr/Prueba_3/prueba_3/prueba/urls.py
from django.urls import path
from . import views

app_name = "prueba"
urlpatterns = [
    # ex: /prueba/
    path("", views.IndexView.as_view(), name="index"),
    path("detail/", views.DetailView.as_view(), name="detail"),
]

PruebaTecnicaJr/Prueba_3/prueba_3/prueba_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prueba/', include('prueba.urls'))
]

PruebaTecnicaJr/Prueba_3/prueba_3/prueba/models.py
from django.db import models

class DetailModel(models.Model):
    detalle = models.CharField(default=None, max_length=100)

PruebaTecnicaJr/Prueba_3/prueba_3/prueba/forms.py
from django import forms

class DetailForm(forms.Form):
    detalle = forms.CharField()

    def __str__(self):
        return str(self.detalle)

PruebaTecnicaJr/Prueba_3/prueba_3/prueba/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse

from .models import DetailModel
from .forms import DetailForm


class IndexView(generic.ListView):
    template_name = "prueba/index.html"
    context_object_name = "texto"

    def get_queryset(self):
        a = DetailModel()
        a.detalle = "Este texto es un ejemplo"
        a.save()
        return a


class DetailView(generic.ListView):
    model = DetailModel
    template_name = "prueba/detail.html"
    form_class = DetailForm

    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST)            
            if form.is_valid():
                return render(request, 'prueba/detail.html', {'form': form})
        else:
            form = self.form_class()

        return render(request, 'prueba/detail.html', {'form': form})

    def get(self, request):
        if request.method == 'GET':
            return HttpResponse("Este es un ejemplo de metodo GET")

PruebaTecnicaJr/Prueba_3/prueba_3/prueba/templates/prueba/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle</title>
</head>
<body>
    <header>
        <h1>{{ form.cleaned_data.detalle }} de metodo POST</h1>
    </header>
    <main>
        <section>
            <form action="">
                <h1>{{ form_get.f }}</h1>
                <input type="submit" value="Metodo get">
            </form>
        </section>
    </main>
</body>
</html>

PruebaTecnicaJr/Prueba_3/prueba_3/prueba/templates/prueba/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prueba</title>
</head>
<body>
    <header>
        <h1>Hola mundo</h1>
    </header>
    <main>
        <section>
            <form action="{% url 'prueba:detail' %}" method="post">
                {% csrf_token %}
                <input type="text" value="{{ texto.detalle }}" name="detalle">
                <input type="submit">
            </form>
        </section>
    </main>
</body>
</html>